---
# handlers file for k8sdeploy
- name: Start kubectl
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
  become: true
- name: Restart docker 
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  become: true

