- name: install docker
  pip:
    name: docker==4.4.4
    executable: pip

- name: Check docker daemon is running.
  service:
    name: docker
    state: started

- name: Pulling Calico images calico/node:v3.16.5.(1/4)
  docker_image:
      name: calico/node
      source: pull
      tag: v3.16.5

- name: Pulling Calico images calico/cni:v3.16.5.(2/4)
  docker_image:
    name: calico/cni
    source: pull
    tag: v3.16.5

- name: Pull Calico images calico/pod2daemon-flexvol:v3.16.5.(3/4)
  docker_image:
    name: calico/pod2daemon-flexvol
    source: pull
    tag: v3.16.5

- name: Pulling Calico image calico/kube-controllers:v3.16.5.(4/4)
  docker_image:
    name: calico/kube-controllers
    source: pull
    tag: v3.16.5