- name: Pull Calico Images.
  include: image-pull.yml

- name: Setup calico on gcp.
  include: install-calico-gcp.yml
  become: yes
  become_user: root
  when:
    - '"{{ platform }}" == "GCP"'

- name: Setup calico on local.
  include: install-calico.yml
  become: yes
  become_user: root
  when:
    - '"{{ platform }}" == "Local"'

- name: Install calicoctl
  include: install_calicoctl.yml
  when:
    - "{{install_calicoctl}} == true"