{{- if and .Values.kubeControllerManager.enabled .Values.kubeControllerManager.endpoints }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "8.kube-prometheus-stack.fullname" . }}-kube-controller-manager
  labels:
    app: {{ template "8.kube-prometheus-stack.name" . }}-kube-controller-manager
    k8s-app: kube-controller-manager
{{ include "8.kube-prometheus-stack.labels" . | indent 4 }}
  namespace: kube-system 
subsets:
  - addresses:
      {{- range .Values.kubeControllerManager.endpoints }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - name: http-metrics
        port: {{ .Values.kubeControllerManager.service.port }}
        protocol: TCP
{{- end }}
