- name: Install python in target node with ansible
  hosts: master,worker
  become: true
  gather_facts: no
  pre_tasks:
  - name: install python
    raw: yum install python3 -y
    args:
      executable: /bin/bash