- name: Copy nginx-controller files to /var/iac/{{cluster_name}}/nginx-controller-bare-metal.yaml in controller
  become: false
  local_action:
    module: copy
    src: files/nginx-controller-bare-metal.yaml
    dest: /var/iac/{{cluster_name}}

- name: Copy role files to /iac/{{cluster_name}}/nginx-controller-bare-metal.yaml in leader
  copy:
    src: files/nginx-controller-bare-metal.yaml
    dest: /var/iac/{{cluster_name}}

- name: Installing nginx-ingress controller pod network
  command: kubectl apply -f /var/iac/{{cluster_name}}/nginx-controller-bare-metal.yaml
  retries: 30
  delay: 2
  register: r1
  until: r1.rc == 0

#- name: Waiting for nginx-ingress controller pods to up and ready.
#  shell: kubectl -n ingress-nginx get pods -A -o json
#  register: kubectl_get_pods
#  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
#  retries: 20
#  delay: 6