---
# tasks file for 9.ingress-nginx
- name: Add nginx helm repo
  shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

- name: Update repo
  shell: helm repo update

- name: Get chart status
  shell: helm list -n ingress-nginx --short | grep ingress
  register: r1
  ignore_errors: true

- name: Installing on namespace ingress-nginx
  shell: helm install ingress ingress-nginx/ingress-nginx --version=4.0.1 --namespace ingress-nginx --create-namespace --set-string controller.service.externalTrafficPolicy=Local --set-string controller.kind=DaemonSet
  when: r1.rc != 0

- name: Upgrading on namespace ingress-nginx
  shell: helm upgrade ingress ingress-nginx/ingress-nginx --version=4.0.1 --namespace ingress-nginx --create-namespace --set-string controller.service.externalTrafficPolicy=Local --set-string controller.kind=DaemonSet
  when: r1.rc == 0