#- name: Add nginx helm repo
#  shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
#
#- name: Update repo
#  shell: helm repo update

- name: Role host-network
  include: host-network.yaml
  become: yes
  become_user: root