{{- if and .Values.kubeScheduler.enabled .Values.kubeScheduler.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "8.kube-prometheus-stack.fullname" . }}-kube-scheduler
  labels:
    app: {{ template "8.kube-prometheus-stack.name" . }}-kube-scheduler
    jobLabel: kube-scheduler
{{ include "8.kube-prometheus-stack.labels" . | indent 4 }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.kubeScheduler.service.port}}
      protocol: TCP
      targetPort: {{ .Values.kubeScheduler.service.targetPort}}
{{- if .Values.kubeScheduler.endpoints }}{{- else }}
  selector:
    {{- if .Values.kubeScheduler.service.selector }}
{{ toYaml .Values.kubeScheduler.service.selector | indent 4 }}
    {{- else}}
    component: kube-scheduler
    {{- end}}
{{- end }}
  type: ClusterIP
{{- end -}}
