apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: echo-server-1
  namespace: abc
  labels:
    app: echo-server-1
spec:
  template:
    metadata:
      name: echo-server-1
      labels:
        app: echo-server-1
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: echo-server-1
          ports:
            - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: echo-server-1

---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-1
  namespace: abc
spec:
  selector:
    app: echo-server-1
  ports:
    - port: 8443
      targetPort: 80
  type: ClusterIP