apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-1
  namespace: abc
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - skalam.info
      secretName: app-secret
  rules:
  - host: skalam.info
    http:
      paths:
      - path: /abc
        pathType: ImplementationSpecific
        backend:
          service:
            name: echo-server-1
            port:
              number: 8080