apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: echo-server-2
  namespace: abc
  labels:
    app: echo-server-2
spec:
  template:
    metadata:
      name: echo-server-2
      labels:
        app: echo-server-2
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: echo-server-2
          ports:
            - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: echo-server-2

---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-2
  namespace: abc
spec:
  selector:
    app: echo-server-2
  ports:
    - port: 1235
      targetPort: 80
  type: ClusterIP