- hosts: localhost
  become: false
  name: Configure Global vars
  tasks:
    - name: Remove Old Global Vars
      file:
        path: $HOME/iac/global-vars.yml
        state: absent
    - name: Copy global vars
      copy:
        src: global-vars.yml
        dest: $HOME/iac/