apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-debug
  labels:
    app: network-debug
spec:
  selector:
    matchLabels:
      name: network-debug
  template:
    metadata:
      labels:
        name: network-debug
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: network-debug
        image: praqma/network-multitool:extra
        resources:
          limits:
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true