---
# tasks file for prom

- name: Make dir at /tmp/kube-prometheous
  file:
    path: /tmp/kube-prometheous
    state: directory
    mode: '1777'

- name: Add repo
  shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: Repo Update
  shell: helm repo update

- name: Check file download status
  stat:
    path: /tmp/kube-prometheous/kube-prometheus-stack
  register: r0

- name: Download helm chart
  shell: helm pull prometheus-community/kube-prometheus-stack --version=18.0.1 --untar --destination=/tmp/kube-prometheous
  when: not r0.stat.exists

- name: Set node port
  template:
    src: values.yaml.j2
    dest: /tmp/kube-prometheous/kube-prometheus-stack/charts/grafana/values.yaml
    force: yes

- name: Get chart status
  shell: helm list -n monitoring --short | grep prom
  register: r1
  ignore_errors: true

- name: Create namespace
  shell: kubectl create ns monitoring

- name: Helm install
  shell: helm install -n monitoring prom /tmp/kube-prometheous/kube-prometheus-stack --values=/tmp/kube-prometheous/kube-prometheus-stack/charts/grafana/values.yaml
  when: r1.rc != 0

- name: Upgrade helm chart
  shell: helm upgrade -n monitoring prom /tmp/kube-prometheous/kube-prometheus-stack --values=/tmp/kube-prometheous/kube-prometheus-stack/charts/grafana/values.yaml
  when: r1.rc == 0