IMAGE_NAME = "generic/centos8"    # Base image of VM CentOS 8 Stream updated
BOX_VERSION = "4.1.2"
HOST_NAME = "controller"

CPU = 2
MEMORY = 4096
HDD = 15
IP = "192.168.56.3"

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ['vagrant-disksize','vagrant-hostmanager']
  config.vm.box = IMAGE_NAME
  config.vm.box_version = BOX_VERSION
  config.vm.host_name = HOST_NAME   #Static hostname of the vm
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.network "private_network", ip: IP
  config.vm.synced_folder ".", "/vagrant"
  config.vm.define HOST_NAME do |i|
    config.vm.provider "virtualbox" do |vm|
      vm.name = HOST_NAME  # VM Name displayed on Virtualbox console.
      vm.gui = false
      vm.memory = MEMORY
      vm.cpus = CPU
    end
    config.vm.provision "shell", inline: <<-SHELL
        sh /vagrant/ShellScripts/update_ssh_config.sh
        #yum install epel-release -y
        #yum update -y
        #yum upgrade -y
        #yum install python3.9 -y
        #su - vagrant -c 'python3.9 -m pip install --user ansible'
        #su - vagrant -c 'ansible --version'
        hostnamectl
    SHELL
  end
end
