IMAGE_NAME = "generic/rhel7"    # Base image of VM which is vagrant box of Ubuntu Bionic 18.04 TLS
NS = 3                          # Specify the the numbers of Slave VMs to create (Example:- 2,3,4)
NM = 1                          # Specify number of master vms to create(Example:-3,4,5 but minimum 3)
MASTER = "master"               # Name of Master VM
SLAVES = "slave"                # Names of Slave VMs(Slave vms will be named as slave1,slave2,slave3 ... )
CPU_MASTER = 2                  # Specify the CPU of master VM(Example :-1,2)
CPU_SLAVE = 1                   # Specify CPU of each slave VMs(Example :-1,2)
MEMORY_MASTER = 4096            # Specify the RAM of master VMs in MB(Example :- 2048,4096)
MEMORY_SLAVE = 2048             # Specify the RAM of each slave VMs in MB(Example :- 2048,4096)
HDD = '15GB'                    # HDD of Each VM (Examples :- "15GB","20GB","30GB")
BOX_VERSION = "3.0.6"
# IP_MASTER = '192.100.100.10'
# IP_SLAVE = '192.100.100.'

Vagrant.configure("2") do |config|
    config.vagrant.plugins = ['vagrant-disksize','vagrant-hostmanager']
    config.ssh.insert_key = false
    config.vm.box_check_update = false
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true  # false to disable update '/etc/hosts' of host with guest VMs dns.
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
    config.disksize.size = HDD
    config.vm.synced_folder ".", "/vagrant", disabled: false
    (1..NM).each do |i|
        config.vm.define MASTER +  "#{i}" do |master|
            master.vm.provider "virtualbox" do |vmm|
                vmm.memory = MEMORY_MASTER
                vmm.cpus = CPU_MASTER
                vmm.gui = false
                vmm.linked_clone = true
            end
            master.vm.box = IMAGE_NAME
            master.vm.box_version = BOX_VERSION
            master.vm.network "private_network", ip: "192.10.10.5"
            master.vm.hostname = MASTER + "#{i}"
            master.vm.provision "shell", inline: <<-SHELL
                sudo cp -R /vagrant/repos/centos.repo /etc/yum.repos.d
                sudo yum repolist
                sudo yum update -y
                sudo yum install python-pip -y
                cd /vagrant
                ./ShellScripts/update_ssh_config.sh
            SHELL
        end
    end

    config.vm.define SLAVES + "1" do |slave|
        slave.vm.provider "virtualbox" do |vms|
            vms.memory = MEMORY_SLAVE
            vms.cpus = CPU_SLAVE
            vms.gui = false
            vms.linked_clone = true
        end
        slave.vm.box = IMAGE_NAME
        slave.vm.box_version = BOX_VERSION
        slave.vm.network "private_network", ip: "192.10.10.10"
        slave.vm.hostname = SLAVES + "1"
        slave.vm.provision "shell", inline: <<-SHELL
             sudo cp -R /vagrant/repos/centos.repo /etc/yum.repos.d
             sudo yum repolist
             sudo yum update -y
             sudo yum install python-pip -y
             cd /vagrant
             ./ShellScripts/update_ssh_config.sh
             # sudo yum install python3 -y
        SHELL
    end
    config.vm.define SLAVES + "2" do |slave|
            slave.vm.provider "virtualbox" do |vms|
                vms.memory = MEMORY_SLAVE
                vms.cpus = CPU_SLAVE
                vms.gui = false
                vms.linked_clone = true
            end
            slave.vm.box = IMAGE_NAME
            slave.vm.box_version = BOX_VERSION
            slave.vm.network "private_network", ip: "192.20.20.20"
            slave.vm.hostname = SLAVES + "2"
            slave.vm.provision "shell", inline: <<-SHELL
                 sudo cp -R /vagrant/repos/centos.repo /etc/yum.repos.d
                 sudo yum repolist
                 sudo yum update -y
                 sudo yum install python-pip -y
                 cd /vagrant
                 ./ShellScripts/update_ssh_config.sh
                 # sudo yum install python3 -y
            SHELL
    end
    config.vm.define SLAVES + "3" do |slave|
            slave.vm.provider "virtualbox" do |vms|
                vms.memory = MEMORY_SLAVE
                vms.cpus = CPU_SLAVE
                vms.gui = false
                vms.linked_clone = true
            end
            slave.vm.box = IMAGE_NAME
            slave.vm.box_version = BOX_VERSION
            slave.vm.network "private_network", ip: "192.30.30.30"
            slave.vm.hostname = SLAVES + "3"
            slave.vm.provision "shell", inline: <<-SHELL
                 sudo cp -R /vagrant/repos/centos.repo /etc/yum.repos.d
                 sudo yum repolist
                 sudo yum update -y
                 sudo yum install python-pip -y
                 cd /vagrant
                 ./ShellScripts/update_ssh_config.sh
                 # sudo yum install python3 -y
            SHELL
    end
end
