kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-nginx
  labels:
    type: local
spec:
#   storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/data/db"