apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume-nginx
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi