apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-certificate
  namespace: g1
spec:
#  isCA: true            # its make certificate valid for signing other certificate
  commonName: maifuj.com
  secretName: tls-secret
  privateKey:
    algorithm: RSA             #ECDSA
  issuerRef:
    name: gcp-le-staging
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - maifuj.com
    - '*.maifuj.com'