apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gcp-le-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: sk.maifujalam@gmail.com
    privateKeySecretRef:
      name: gcp-le-staging   # Lets encrypt account key
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: openshift-325202
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json