---
  - name: Making directory .kube
    file:
      path: "{{ansible_facts.env.HOME}}/.kube"
      state: directory


  - name: Copy the required config file.
    become: true
    copy:
      remote_src: yes  
      src: /etc/kubernetes/admin.conf 
      dest: "{{ansible_facts.env.HOME}}/.kube/config"

  - name: Copy kubeconfig file to $HOME/k8s-clusters/{{cluster_name}}/config in controller
    copy:
      src: "{{ansible_facts.env.HOME}}/.kube/config"
      dest: "{{ansible_facts.env.HOME}}/k8s-clusters/{{cluster_name}}/config"
      remote_src: true

  - name: Do auto completion
    blockinfile:
      path: ~/.bashrc
      insertafter: EOF
      block: |
        alias k='kubectl'
        source <(kubectl completion bash)
        complete -F __start_kubectl k

