- name: Copying repos of centos-8
  copy:
    src: files/repos-centos8/yum.repos.d/
    dest: /etc/yum.repos.d
    force: yes

- name: Copy repo keys
  copy:
    src: files/repos-centos8/rpm-gpg/
    dest: /etc/pki/rpm-gpg/
    force: yes