- name: Debug touch
  shell: touch /tmp/aa

- name: Copying repos of centos-8
  copy:
    src: files/repos-centos8/yum.repos.d/
    dest: /etc/yum.repos.d
    force: yes

- name: Copy repo keys
  copy:
    src: files/repos-centos8/rpm-gpg/
    dest: /etc/pki/rpm-gpg/
    force: yes

- name: Add K8s repo
  yum_repository:
    name: kubernetes
    description: kubernetes YUM repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude:
      - kubelet
      - kubeadm
      - kubectl
    gpgcheck: yes
    enabled: yes

- name: update all packages
  yum:
    name: '*'
    state: latest
    exclude: kube*