#- easy_install:
#    name: pip
#    state: latest
- name: Disable SELinux
  become: yes
  selinux:
    state: disabled
- name: Chane SELinux Config file.
  shell: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
  become: true
