#- name: Remove swapfile from /etc/fstab
#  mount:
#    name: swap
#    fstype: swap
#    state: absent
#- name: Disable swap
#  command: swapoff -a
#  become: true

- name: Diable swap:- temporarry(1/2)
  become: true
  shell: |
    swapoff -a

- name: Disable swap:- permanent (2/2)
  become: true
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    line: '#swap offed'