- name: Letting iptables see bridged traffic
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
    force: yes

- name: Reload sysctl config for iptables
  command: sysctl --system

- name: Check ip forwarding
  shell: cat /proc/sys/net/ipv4/ip_forward
  register: r1

- debug:
    msg: "{{r1}}"
  name: printing r1
- debug:
    msg: "IP Forwarding is Enabled"
  when: '{{r1.stdout}} == 1'

- name: check ip forward
  fail:
    msg: "Error! IP Forwarding is disabled"
  when: r1.stdout=='0'
