{{- if and .Values.alertmanager.enabled .Values.global.rbac.create .Values.global.rbac.pspEnabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "8.kube-prometheus-stack.fullname" . }}-alertmanager
  namespace: {{ template "8.kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "8.kube-prometheus-stack.name" . }}-alertmanager
{{ include "8.kube-prometheus-stack.labels" . | indent 4 }}
rules:
{{- $kubeTargetVersion := default .Capabilities.KubeVersion.GitVersion .Values.kubeTargetVersionOverride }}
{{- if semverCompare "> 1.15.0-0" $kubeTargetVersion }}
- apiGroups: ['policy']
{{- else }}
- apiGroups: ['extensions']
{{- end }}
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "8.kube-prometheus-stack.fullname" . }}-alertmanager
{{- end }}
