{{- if and .Values.kubeEtcd.enabled .Values.kubeEtcd.endpoints }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "8.kube-prometheus-stack.fullname" . }}-kube-etcd
  labels:
    app: {{ template "8.kube-prometheus-stack.name" . }}-kube-etcd
    k8s-app: etcd-server
{{ include "8.kube-prometheus-stack.labels" . | indent 4 }}
  namespace: kube-system
subsets:
  - addresses:
      {{- range .Values.kubeEtcd.endpoints }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - name: http-metrics
        port: {{ .Values.kubeEtcd.service.port }}
        protocol: TCP
{{- end }}
