apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-2
spec:
  type: NodePort
  selector:
    app: hello-kubernetes-2
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30303

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes-2
  template:
    metadata:
      labels:
        app: hello-kubernetes-2
    spec:
      containers:
        - name: hello-kubernetes-2
          image: paulbouwer/hello-kubernetes:1.5
          ports:
            - containerPort: 8080
      nodeName: worker-1