- name: Check calicoctl
  shell: calicoctl node status
  register: r1
  ignore_errors: yes

- debug:
    msg: "{{r1}}"

- name: downloading calicoctl binary
  get_url:
    url: "{{url}}"
    dest: "{{dest}}"
    mode: 777
  when: r1.rc != 0

- name: Node status
  shell: calicoctl node status
  register: nodestatus

- debug:
    msg: "{{ nodestatus.stdout.split('\n') }}"
