apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-host-network
  namespace: sandbox
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - skalam.info
      secretName: app-secret
  rules:
  - host: skalam.info
    http:
      paths:
      - path: /host-network
        pathType: Prefix
        backend:
          service:
            name: echo-server-host-network
            port:
              number: 8080

---
# NOTE: TLS certificate only works with rules defined with matching host with tls->hosts.


#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: service-host-network
#  namespace: sandbox
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#  tls:
#    - hosts:
#        - skalam.info
#      secretName: app-secret
#  rules:
#  - http:
#      paths:
#      - path: /host-network
#        pathType: Prefix
#        backend:
#          service:
#            name: echo-server-host-network
#            port:
#              number: 8080