apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-certificate
  namespace: a1
spec:
  isCA: true            # its make certificate valid for signing other certificate
  secretName: tls-secret
  commonName: example.com
  duration: 8760h         # 720=1-month,default 90 days,8760h=1-year,43800h=5-year,
  privateKey:
    algorithm: RSA             #ECDSA
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - '*.example.com'