- name: Configure RHEL
  hosts: master,worker
  become: false
  tasks:
    - import_role:
        name: 1.rhel_initial_config

- name: Install k8s
  hosts: master,worker
  become: false
  tasks:
    - name: Include vars
      include_vars: ./global-vars.yaml
    - include_role:
        name: 2.k8sdeploy

- name: Install k8s
  hosts: master
  become: false
  tasks:
    - name: Include vars
      include_vars: ./global-vars.yaml
    - include_role:
        name: 3.init

- name: Install CNI
  hosts: master
  become: false
  tasks:
    - name: Include vars
      include_vars: ./global-vars.yaml
    - include_role:
        name: 4.cni

- name: Join Worker
  hosts: worker
  become: false
  tasks:
    - name: Include vars
      include_vars: ./global-vars.yaml
    - include_role:
        name: 5.join-worker

- name: Install Dashboard
  hosts: master
  become: false
  tasks:
    - name: Include vars
      include_vars: ./global-vars.yaml
    - include_role:
        name: 6.dashboard

- name: Install helm
  hosts: master
  become: false
  tasks:
    - name: Include vars
      include_vars: ./global-vars.yaml
    - include_role:
        name: 7.helm-install

- name: Install prometheous stack
  hosts: master
  become: false
  tasks:
    - name: Include vars
      include_vars: ./global-vars.yaml
    - include_role:
        name: 8.kube-prometheus

#- name: etcd tuning
#  hosts: master
#  become: yes
#  tasks:
#    - name: Include vars
#      include_vars: /var/iac/global-vars.yaml
#    - include_role:
#        name: etcd-tuning

#- name: Install nfs all
#  hosts: master,worker
#  become: yes
#  tasks:
#    - name: Include vars
#      include_vars: /var/iac/global-vars.yaml
#    - include_role:
#        name: nfs-client-role
#
#- name: Install nfs
#  hosts: master
#  become: yes
#  tasks:
#    - name: Include vars
#      include_vars: /var/iac/global-vars.yaml
#    - include_role:
#        name: NFS_Dynamic_Storage_Provsion_Role

#- name: Install etcdctl
#  hosts: master
#  become: yes
#  tasks:
#    - name: Include vars
#      include_vars: /var/iac/global-vars.yaml
#    - include_role:
#        name: etcdctl

#- name: Install cert manager
#  hosts: master
#  become: yes
#  tasks:
#    - name: Include vars
#      include_vars: /var/iac/global-vars.yaml
#    - include_role:
#        name: 9.cert-manager.yaml

- name: Install nginx-ingrss controller
  hosts: master
  become: false
  tasks:
    - name: Include vars
      include_vars: ./global-vars.yaml
    - include_role:
        name: 10.ingress-nginx