#- name: Write logs /tmp
#  log_plays:
#    log_folder: /tmp

- name: Checking helm
  shell: which helm
  register: r1
  ignore_errors: yes

- debug:
    msg: "{{r1}}"

- name: Creating temp dir at /tmp/helm/
  file:
    state: directory
    path: /tmp/helm/
    mode: '1777'

- name: Check if file is pulled
  stat:
    path: /tmp/helm/helm-v{{helm_version}}-linux-amd64.tar.gz
  register: r2
  ignore_errors: true


- name: downloading helm binary
  get_url:
    url: "https://get.helm.sh/helm-v{{helm_version}}-linux-amd64.tar.gz"
    mode: '1777'
    dest: /tmp/helm/helm-v{{helm_version}}-linux-amd64.tar.gz
  when:
    - r1.rc != 0
    - not r2.stat.exists
  ignore_errors: true


- name: Untar to /tmp
  ansible.builtin.unarchive :
    src: /tmp/helm/helm-v{{helm_version}}-linux-amd64.tar.gz
    dest: /tmp/helm
    remote_src: yes


- name: Copy from tmp to /usr/local/bin
  become: true
  copy:
    src: /tmp/helm/linux-amd64/helm
    dest: /usr/local/bin
    mode: '777'
    force: yes
    remote_src: true
  when:
    - r1.rc != 0

- name: Copy from tmp to /usr/bin
  become: true
  copy:
    src: /tmp/helm/linux-amd64/helm
    dest: /usr/bin
    mode: '777'
    force: yes
    remote_src: true
  when:
    - r1.rc != 0


- name: helm version
  shell: helm version
  register: helm_version

- debug:
    msg: "{{ helm_version.stdout.split('\n') }}"

- name: Add helm repo
  shell: helm repo add bitnami https://charts.bitnami.com/bitnami

- name: Repo Update
  shell: helm repo update