apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-tcp-6379
  namespace: production
spec:
  selector: app == 'customer'
  ingress:
    - action: Allow
      protocol: TCP
      source:
        selector: app == 'customer'
      destination:
        ports:
          - 80