apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-certificate
  namespace: a1
spec:
#  isCA: true            # its make certificate valid for signing other certificate
  commonName: "example.com"
  secretName: tls-secret
  privateKey:
    algorithm: RSA             #ECDSA
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - example.com