IMAGE_NAME = "generic/rhel8"    # Base image of VM which is vagrant box of Ubuntu Bionic 18.04 TLS
NS = 3                          # Specify the the numbers of Slave VMs to create (Example:- 2,3,4)
NM = 1                          # Specify number of master vms to create(Example:-3,4,5 but minimum 3)
MASTER = "master"               # Name of Master VM
SLAVES = "slave"                # Names of Slave VMs(Slave vms will be named as slave1,slave2,slave3 ... )
CPU_MASTER = 2                  # Specify the CPU of master VM(Example :-1,2)
CPU_SLAVE = 1                   # Specify CPU of each slave VMs(Example :-1,2)
MEMORY_MASTER = 4096            # Specify the RAM of master VMs in MB(Example :- 2048,4096)
MEMORY_SLAVE = 2048             # Specify the RAM of each slave VMs in MB(Example :- 2048,4096)
HDD = '15GB'                    # HDD of Each VM (Examples :- "15GB","20GB","30GB")
BOX_VERSION = "3.3.2"
IP_MASTER = '10.30.0.5'
IP_WORKER = ['10.30.0.10','10.30.1.20','10.30.1.30']

Vagrant.configure("2") do |config|
    config.vagrant.plugins = ['vagrant-disksize','vagrant-hostmanager']
    config.ssh.insert_key = false
    config.vm.box_check_update = false
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true  # false to disable update '/etc/hosts' of host with guest VMs dns.
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
    config.disksize.size = HDD
    config.vm.synced_folder ".", "/vagrant", disabled: false
    (1..NM).each do |i|
        config.vm.define MASTER +  "" do |master|
            master.vm.provider "virtualbox" do |vmm|
                vmm.memory = MEMORY_MASTER
                vmm.cpus = CPU_MASTER
                vmm.gui = false
                vmm.linked_clone = true
            end
            master.vm.box = IMAGE_NAME
            master.vm.box_version = BOX_VERSION
            master.vm.network "private_network", ip: IP_MASTER
            master.vm.hostname = MASTER
            master.vm.provision "shell", inline: <<-SHELL
                sudo yum install epel-release -y
                sudo yum repolist
                sudo yum update -y
                cd /vagrant
                ./ShellScripts/update_ssh_config.sh
            SHELL
        end
    end

    (1..NS).each do |j|
    config.vm.define SLAVES + "#{j}" do |slave|
            slave.vm.provider "virtualbox" do |vms|
                vms.memory = MEMORY_SLAVE
                vms.cpus = CPU_SLAVE
                vms.gui = false
            end
            slave.vm.box = IMAGE_NAME
            slave.vm.box_version = BOX_VERSION
            slave.vm.network "private_network", ip: IP_WORKER[j]
            slave.vm.hostname = SLAVES + "#{j}"
            slave.vm.provision "shell", inline: <<-SHELL
                 sudo yum install epel-release -y
                 sudo yum repolist
                 sudo yum update -y
                 cd /vagrant
                 ./ShellScripts/update_ssh_config.sh
            SHELL
        end
    end
end
