{{- if and .Values.grafana.enabled .Values.grafana.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "8.kube-prometheus-stack.fullname" . }}-grafana
  namespace: {{ template "8.kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "8.kube-prometheus-stack.name" . }}-grafana
{{ include "8.kube-prometheus-stack.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  namespaceSelector:
    matchNames:
      - {{ printf "%s" (include "8.kube-prometheus-stack.namespace" .) | quote }}
  endpoints:
  - port: {{ .Values.grafana.service.portName }}
    {{- if .Values.grafana.serviceMonitor.interval }}
    interval: {{ .Values.grafana.serviceMonitor.interval }}
    {{- end }}
    path: {{ .Values.grafana.serviceMonitor.path | quote }}
{{- if .Values.grafana.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.grafana.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.grafana.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.grafana.serviceMonitor.relabelings | indent 6 }}
{{- end }}
{{- end }}
